import { darkTheme, lightTheme } from './themes';
export { darkTheme, lightTheme };

export const API_CONFIG = {
  BASE_URL: 'https://ve.dolarapi.com/v1',
  FETCH_TIMEOUT: 15000,
  HISTORICAL_FETCH_TIMEOUT: 10000,
  HISTORICAL_API_CACHE_TTL: 60 * 60 * 1000,
  HISTORICAL_LOCAL_RETENTION_DAYS: 365,
  UPDATE_CACHE_TTL: 30 * 60 * 1000,
  OFFLINE_RETRY_INITIAL_DELAY: 30000,
  OFFLINE_RETRY_MAX_DELAY: 300000,
  OFFLINE_RETRY_MAX_ATTEMPTS: 10,
  HISTORICAL_CHART_ENTRIES: 5,
};

